### ISSUE TITLE
Static Web Apps CLI barfs if we feed it https

### ISSUE THREAD

**Issue by xela-trawets** [Apress/beginning-azure-static-web-apps#4]
Chapter 5 introduces the swa cli

I had trouble following instructions (in this case from the book)
because the swa cli would just exit and drop out onto the shell prompt.

spent a while trying to fiddle with staticwebapp.config.json - but that was a red herring.
turns out avoiding https worked for me.

**Comment by xela-trawets** [comment]
detailed well here
https://github.com/Azure/static-web-apps-cli/issues/610
https://twitter.com/Stacy_Cash/status/1595445964751372294?s=20&t=vWEfOcD-NB8VWPucXjT7MA

**Comment by pmarangoni** [comment]
Detailed well? No so much. What do you mean "avoiding https worked for me"?

**Comment by xela-trawets** [comment]
You have a point, I just looked again and its not very clear in hindsight.

As I remember this, the issue is that the emulator needs a certificate, and we need to trust that certificate. Additionally CORS (by default) wants all addresses to have a common origin (that includes the protocol and the port). So we cannot easily mix HTTP and HTTPS. 

Anyway, in the end I ran the API and the Client using Http  - not Https, the SWA cli "plumbing" then worked without figuring out how to set up the certificates.

Lots has changed post-dotnet 8, with the "dotnet-isolated" functions runtime.

**Comment by pmarangoni** [comment]
What changes are required to run the API and Client with http?

**Comment by xela-trawets** [comment]
I didn't save everything nor did I do everything in order when I did this a while back. 

But I just downloaded the chapter-5 code and had a go.
versions..
Welcome to Azure Static Web Apps CLI (2.0.1)
Azure Functions Core Tools
Core Tools Version:       4.0.6518 Commit hash: N/A +74ed9095fdd6c5326276aae6b8a7d41ccbdeb6aa (64-bit)
Function Runtime Version: 4.35.4.23179

In the API csproj I had to update this.. 
<PackageReference Include="Microsoft.NET.Sdk.Functions" Version="4.6.0" />

Then I ran
chapter-5>swa start http://localhost:5001

(the port for http is from the localsettings.json file in the client project)

And that worked for me. 
You have to open the browser and go to http://localhost:4280 otherwise the http client wont see the API through the SWA, (reminds me of Zaphod needing to leave a building through the window in hitchhikers guide to the galaxy).



The output from SWA shows the following:
`Azure Static Web Apps emulator started at http://localhost:4280. Press CTRL+C to exit.

GET http://localhost:5001/ (proxy)
(node:34096) [DEP0060] DeprecationWarning: The `util._extend` API is deprecated. Please use Object.assign() instead.
GET http://localhost:4280/ - 304
GET http://localhost:5001/_framework/aspnetcore-browser-refresh.js (proxy)
GET http://localhost:5001/css/bootstrap/bootstrap.min.css (proxy)
GET http://localhost:4280/_framework/aspnetcore-browser-refresh.js - 200
GET http://localhost:4280/css/bootstrap/bootstrap.min.css - 200
GET http://localhost:5001/css/app.css (proxy)
GET http://localhost:5001/Client.styles.css (proxy)
GET http://localhost:5001/_framework/blazor.webassembly.js (proxy)
GET http://localhost:4280/css/app.css - 304
GET http://localhost:5001/_vs/browserLink (proxy)
GET http://localhost:4280/Client.styles.css - 304
GET http://localhost:5001/css/open-iconic/font/css/open-iconic-bootstrap.min.css (proxy)
GET http://localhost:4280/_framework/blazor.webassembly.js - 304
GET http://localhost:4280/_vs/browserLink - 304
GET http://localhost:4280/css/open-iconic/font/css/open-iconic-bootstrap.min.css - 304
GET http://localhost:5001/_framework/blazor.boot.json (proxy)
GET http://localhost:4280/_framework/blazor.boot.json - 304
GET http://localhost:5001/favicon.ico (proxy)
GET http://localhost:5001/_framework/dotnet.js (proxy)`
etc.

the Azure function window shows

[2024-11-21T01:58:58.259Z] Found C:\Users\AlexA\Downloads\Chap5Demo\chapter-5\Api\Api.csproj. Using for user secrets file configuration.

Functions:

        Function1: [GET,POST] http://localhost:7071/api/Function1

        WeatherForecast: [GET] http://localhost:7071/api/weather-forecast/{daysToForecast=5}

For detailed output, run func with --verbose flag.
[2024-11-21T01:59:09.450Z] Host lock lease acquired by instance ID '00000000000000000000000052D94FE9'.
[2024-11-21T01:59:47.920Z] Executing 'WeatherForecast' (Reason='This function was programmatically called via the host APIs.', Id=133bdefb-218a-462d-b89f-3427e46d6504)
[2024-11-21T01:59:47.990Z] Executed 'WeatherForecast' (Succeeded, Id=133bdefb-218a-462d-b89f-3427e46d6504, Duration=127ms)
etc

**Comment by xela-trawets** [comment]
The latest "isolated-process" model for azure functions does some things like binding rather differently.
[https://learn.microsoft.com/en-us/azure/azure-functions/dotnet-isolated-process-guide?tabs=hostbuilder%2Cwindows](url)

Most folks I know waited before jumping in to azure functions, due to the bewildering plethora of conflicting models and versions of the multiple parts. There are at least three ways to look at Http responses ( IActionResult,  (Typed)Results, and httpresponsedata )

But It looks like the fog is lifting - maybe "Aspire" will help.

**Comment by xela-trawets** [comment]
so to be clear 
1. Took the chaper-5 code from the original repo
2. updated API csproj with   `<PackageReference Include="Microsoft.NET.Sdk.Functions" Version="4.6.0" />`
3. updated SWA to latest
4. updated Azure Functions Core Tools to latest
5. Started both the API and the Client running together (fiddled with the start config in VS)
6. ran "swa start http://localhost:5001/" in the chapter-5 folder
7. opened http://localhost:4280/ in edge

**Comment by pmarangoni** [comment]
Thanks for jumping and trying to help. I appreciate it. I will give it another shot next week when I have a chance. So far though, I'm really surprised that anyone would bother architecting anything this way.

I'm really disappointed with the author's complete lack of participation too.

**Comment by xela-trawets** [comment]
You are welcome, I enjoyed looking at this again. Hope it works for you. I find it hard to figure out why when it doesn't though.

Your point about why use something so mad is well taken. There has been a backlash against serverless architecture [https://news.ycombinator.com/item?id=39381835](url)

Despite everything I sort of enjoy the madness of Azure functions, because it is new and different.

**Comment by pmarangoni** [comment]
I've decided to abandon this book. Too many issues, and it's clearly not compatible with current versions. I was hoping to glean some good info on Azure, but I'm going to try a few simpler approaches for the time being.
Thanks again!

**Comment by xela-trawets** [comment]
A more recent book is by Mark Price https://www.packtpub.com/en-us/product/apps-and-services-with-net-8-9781837637133 . It contains just enough on everything to get going, wide but deep enough to be useful.

**Comment by pmarangoni** [comment]
I've gone through other books by Mark. Generally, quite good, but like other books, as soon as it's a few months beyond published date, things tend to require plenty of troubleshooting to get samples working with updated platforms.

I went through his book [C#12 and .NET 8 - Modern Cross-Platform Development Fundamentals](https://www.packtpub.com/en-us/product/c-12-and-net-8-modern-cross-platform-development-fundamentals-9781837631988) a few months ago, and there were quite a few issues that he had to address on GitHub to get things working. Looking at that site now, I see that he just released a new version of that book for C# 13 & .NET 9

**Comment by xela-trawets** [comment]
I should take a look at that, thanks.

**Comment by pmarangoni** [comment]
I just pre-ordered this one: https://a.co/d/3W16l9F
